### ISSUE TITLE
real-time video straming for mobile devices

### ISSUE THREAD

**Issue by ThomasLengeling** [gerardobort/ofxStereoCam180#1]
Hi great addon.

I just bought the fish-eye cameras that you posted on the addon. Did you by chance get into the streaming for mobiles devices?. I've loved to try it out.
Thank you!.

**Comment by gerardobort** [comment]
Hi @ThomasLengeling, thanks!

Yes, I've done several tests for different purposes.  It depends on what you're looking for (quality/lag) and the budget.
For example, you can do streaming of 2 raw camera images using `m-jpeg` which is pretty good on a RaspberryPi3 - but not so smooth.  It's like a surveillance camera quality - I did that with a simple flask server.
Or.. you can have a powerful barebone PC and preprocess the transformations on the server side and just stream that output.
If you look for mobile cross-compatibility, Wowza would be a good choice.
I couldn't find an acceptable `ffmpeg` encoding configuration for zero-lag real-time streaming.  But I haven't spent too much time on it.

Cheers,

**Comment by ThomasLengeling** [comment]
Thank you!, Have you tried out Wowza?, I got to run on Linux, but didn't quite get how to stream in real time from openFrameworks to Wowza. Any suggestions on that?. 
I have live streaming setup from Mac to Android with  [TCPSyphon](http://techlife.sg/TCPSyphon) and [TLSyphonViewer](http://techlife.sg/TLSyphonViewer/)

**Comment by gerardobort** [comment]
Yes... you can take any ffmpeg udp stream from Wowza and broadcast it in different formats, for iOS and Android easily, don't remember the details I did it couple of years ago.
Syphon is great, but only for Mac 😞

**Comment by ThomasLengeling** [comment]
Ohh I see, well I got it to work using the ofxHTTP addon + syphon.
Thank you!
